"""Initial migration

Revision ID: 4d7a79ea3de8
Revises: 
Create Date: 2025-01-03 15:48:02.812092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7a79ea3de8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('project_managers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('project_manager_name', sa.String(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customer_name'], ['customers.name'], ),
    sa.ForeignKeyConstraint(['project_manager_name'], ['project_managers.name'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('task_description', sa.String(), nullable=True),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['customer_name'], ['customers.name'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_entries')
    op.drop_table('projects')
    op.drop_table('project_managers')
    op.drop_table('customers')
    # ### end Alembic commands ###
