"""Update models with proper relationships

Revision ID: 8c1328f972dc
Revises: 4d7a79ea3de8
Create Date: 2025-01-03 15:51:45.212449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1328f972dc'
down_revision: Union[str, None] = '4d7a79ea3de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
